apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybillingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybillingapp
  template:
    metadata:
      labels:
        app: mybillingapp
    spec:
      containers:
        - name: mybillingapp
          image: swe40006billingacr.azurecr.io/mybillingapp:latest
          ports:
            - containerPort: 8080
