version: '3.8'

services:
  db:
    build:
      context: . # Build context is the root of the projects
      dockerfile: db.Dockerfile # Points to your new Dockerfile
    container_name: my_postgres
    environment:
      POSTGRES_DB: cafe
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- /home/circleci/project/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: swe40006_devops-backend:latest
    container_name: billing_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: cafe
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_SSLMODE: disable
      DB_PORT: 5432
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/menu"]
      interval: 10s
      timeout: 5s
      retries: 20 # <--- Increased retries to 20 (total check time ~200s after start_period)
      start_period: 10s

volumes:
  pgdata: