version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_DB: cafe
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .          # Root of project, so templates and backend are visible
      dockerfile: backend/Dockerfile
    image: swe40006_devops-backend:latest      
    container_name: billing_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: cafe
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_SSLMODE: disable  
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./templates
      dockerfile: Dockerfile
    image: swe40006_devops-frontend:latest     
    container_name: html_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000

volumes:
  pgdata:
