version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_DB: cafe
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: swe40006_devops-backend:latest
    container_name: billing_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: cafe
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_SSLMODE: disable
    volumes:
      - ./backend:/app
      - ./templates:/app/templates:ro
    ports:
      - "5000:5000"
    command: ["python", "billing.py"]

  frontend:
    build:
      context: ./templates
      dockerfile: Dockerfile
    image: swe40006_devops-frontend:latest
    container_name: html_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000

  selenium_tests:
    image: swe40006billingacr.azurecr.io/food-billing-selenium-tests:latest
    depends_on:
      - frontend
      - backend
    environment:
      - APP_URL=http://frontend:3000
    volumes:
      - ./test-results:/app

volumes:
  pgdata:
