version: '3.8'

services:
  backend:
    image: swe40006_devops-backend:latest
    ports:
      - "5000:5000"

  frontend:
    image: swe40006_devops-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000

  selenium_tests:
    image: swe40006billingacr.azurecr.io/food-billing-selenium-tests:latest  # Replace with actual tag if needed
    depends_on:
      - frontend
      - backend
    environment:
      - APP_URL=http://frontend:3000
    volumes:
      - ./test-results:/app
