version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  build_test_push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          command: docker build -t $ACR_NAME.azurecr.io/foodbilling:latest -f templates/Dockerfile .
      - run:
          name: Run Tests
          command: echo "Run your Selenium or unit tests here"
      - run:
          name: Docker Login
          command: echo $AZURE_PASSWORD | docker login $ACR_NAME.azurecr.io -u $AZURE_USERNAME --password-stdin
      - run:
          name: Docker Push
          command: docker push $ACR_NAME.azurecr.io/foodbilling:latest

workflows:
  build_and_deploy:
    jobs:
      - build_test_push
