version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      # ls -al debug step from before is helpful, keep it for now
      - run:
          name: List files in build working directory
          command: ls -al ~/project
      - run:
          name: Build Docker Compose services
          # ls -al confirmed docker-compose.yml is at root, so -f is optional but harmless
          command: |
            docker-compose -f ~/project/docker-compose.yml build
            docker save swe40006_devops-backend:latest -o backend.tar
            docker save swe40006_devops-frontend:latest -o frontend.tar
      - persist_to_workspace:
          root: ~/project
          paths:
            - backend.tar
            - frontend.tar

  test:
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker

      # ls -al debug step - keep or remove as needed
      - run:
          name: List files in test working directory
          command: ls -al ~/project

      - run:
          name: Load Docker images (backend/frontend)
          command: |
            docker load -i ~/project/backend.tar
            docker load -i ~/project/frontend.tar

      # --- Start and WAIT for services using Healthchecks ---
      # IMPORTANT: Ensure docker-compose.yml has healthchecks defined for 'db' and 'backend'
      # IMPORTANT: Ensure backend service in docker-compose.yml has depends_on: db
      - run:
          name: Start services and wait for healthchecks
          # This command will block until all services with healthchecks
          # that the job depends on are healthy.
          command: docker-compose -f ~/project/docker-compose.yml up -d --wait
      # --- End Start and WAIT step ---

      # --- Run Integration Tests (Selenium) ---
      # Now that services are healthy, tests can run
      # IMPORTANT: Increase the Selenium WebDriverWait timeout in your test code if needed
      - run:
          name: Run integration tests (Selenium)
          command: |
            DC_NETWORK=$(docker network ls -f name=.*_default --format "{{.Name}}" | head -n 1)
            echo "Running tests on network: $DC_NETWORK"
            docker run \
              --rm \
              --network $DC_NETWORK \
              --shm-size="2g" \
              -e APP_URL="http://backend:5000/" \ # Verify backend:5000 matches your docker-compose
              food-billing-selenium-tests:latest

      # --- Capture Backend Logs (Keep this!) ---
      - run:
          name: Capture Backend Logs
          command: docker-compose -f ~/project/docker-compose.yml logs backend
          when: always # Always run this step

      # Optional: Capture DB Logs on failure too
      - run:
          name: Capture DB Logs
          command: docker-compose -f ~/project/docker-compose.yml logs db
          when: always # Always run this step

      # Optional: Add steps here to store test results or artifacts if your tests generate them

  # ... push and deploy jobs ...
  push:
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker
      - run:
          name: Load Docker images
          command: |
            docker load -i ~/project/backend.tar
            docker tag swe40006_devops-backend:latest $ACR_NAME.azurecr.io/swe40006_devops-backend:latest

            docker load -i ~/project/frontend.tar
            docker tag swe40006_devops-frontend:latest $ACR_NAME.azurecr.io/swe40006_devops-frontend:latest
      - run:
          name: Push backend to ACR
          command: |
            echo $AZURE_PASSWORD | docker login $ACR_NAME.azurecr.io -u $AZURE_USERNAME --password-stdin
            docker push $ACR_NAME.azurecr.io/swe40006_devops-backend:latest
      - run:
          name: Push frontend to ACR
          command: |
            docker push $ACR_NAME.azurecr.io/swe40006_devops-frontend:latest

  deploy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Azure CLI and Kubectl
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

            KUBECTL_VERSION=$(curl -sL https://dl.k8s.io/release/stable.txt)
            echo "Installing kubectl version $KUBECTL_VERSION"
            curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/kubectl
      - run:
          name: Login to Azure and set AKS credentials
          command: |
            az login --service-principal -u $AZURE_SP_APP_ID -p $AZURE_SP_CLIENT_SECRET --tenant $AZURE_TENANT_ID
            az aks get-credentials --resource-group "$AZURE_RESOURCE_GROUP" --name "$AKS_CLUSTER_NAME" --overwrite-existing
      - run:
          name: Deploy backend and frontend to AKS
          command: |
            kubectl apply -f k8s/db-secret.yaml
            kubectl apply -f k8s/backend-deployment.yaml
            kubectl apply -f k8s/backend-service.yaml
            kubectl apply -f k8s/frontend-deployment.yaml
            kubectl apply -f k8s/frontend-service.yaml
      - run:
          name: Restart Deployments to Pick Up Changes
          command: |
            kubectl rollout restart deployment backend-deployment
            kubectl rollout restart deployment frontend-deployment


workflows:
  build_test_push:
    jobs:
      - build
      - test:
          requires:
            - build
      - push:
          requires:
            - test
      - deploy:
          requires:
            - push