version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      # ls -al debug step from before is helpful, keep it for now
      - run:
          name: List files in build working directory
          command: ls -al ~/project
      - run:
          name: Build Docker Compose services
          # ls -al confirmed docker-compose.yml is at root, so -f is optional but harmless
          command: |
            docker-compose -f ~/project/docker-compose.yml build
            docker save swe40006_devops-backend:latest -o backend.tar
            docker save swe40006_devops-frontend:latest -o frontend.tar
      - persist_to_workspace:
          root: ~/project
          paths:
            - backend.tar
            - frontend.tar

  test:
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker

      # ls -al debug step - keep or remove as needed
      - run:
          name: List files in test working directory
          command: ls -al ~/project
      
      - run:
          name: Build Selenium test runner image
          command: docker build -t food-billing-selenium-tests -f tests/Dockerfile tests/

      - run:
          name: Load Docker images (backend/frontend)
          command: |
            docker load -i ~/project/backend.tar
            docker load -i ~/project/frontend.tar

      # --- Start and WAIT for services using Healthchecks ---
      # IMPORTANT: Ensure docker-compose.yml has healthchecks defined for 'db' and 'backend'
      # IMPORTANT: Ensure backend service in docker-compose.yml has depends_on: db
      - run:
          name: Start services and wait for healthchecks
          # This command will block until all services with healthchecks
          # that the job depends on are healthy.
          command: docker-compose -f ~/project/docker-compose.yml up -d --wait
      # --- End Start and WAIT step ---

      # --- Run Integration Tests (Selenium) ---
      # Now that services are healthy, tests can run
      # IMPORTANT: Increase the Selenium WebDriverWait timeout in your test code if needed
      - run:
          name: Start services and wait for healthchecks
          command: docker-compose -f ~/project/docker-compose.yml up -d --wait

      # --- NEW Step to Verify Database ---
      - run:
          name: Verify Database Schema and Data
          command: |
            #!/bin/bash -eo pipefail
            echo "--- Verifying Database Setup ---"

            # Check if the menu_items table exists using psql inside the container
            echo "Checking if 'menu_items' table exists in 'cafe' database..."
            # Use docker-compose exec to run commands inside the 'db' service container
            # Connect as 'admin' user to 'cafe' database
            # -c '\d menu_items' lists details about the table
            docker-compose -f ~/project/docker-compose.yml exec db \
              psql -U admin -d cafe -c '\d menu_items' || {
                echo "Error: 'menu_items' table does NOT exist! Database initialization script failed."
                exit 1 # Fail the CI step if the table is not found
              }
            echo "'menu_items' table found."

            # Check if data was inserted by counting rows
            echo "Checking row count in 'menu_items' table..."
            # -tA flags format the output to give just the value
            ROW_COUNT=$(docker-compose -f ~/project/docker-compose.yml exec db \
              psql -U admin -d cafe -tA -c 'SELECT COUNT(*) FROM menu_items;') || {
                echo "Error: Failed to get row count from 'menu_items'!"
                exit 1 # Fail the CI step if the count query fails
              }
            echo "Row count: $ROW_COUNT"

            # Optional: Add an assertion for the expected number of rows
            EXPECTED_ROWS=8 # Adjust based on how many INSERTs are in your SQL file
            if [[ "$ROW_COUNT" -lt "$EXPECTED_ROWS" ]]; then
              echo "Warning: Expected at least $EXPECTED_ROWS rows, but found only $ROW_COUNT."
              # You might want to exit 1 here instead of just warning if data is essential
              # exit 1
            fi

            # Optional: Display some data (useful for debugging, can be verbose)
            # echo "Sample data:"
            # docker-compose -f ~/project/docker-compose.yml exec db \
            #   psql -U admin -d cafe -c 'SELECT id, name, price FROM menu_items LIMIT 5;'


            echo "--- Database Verification Complete ---"
      # --- END NEW Step ---
      
      - run:
          name: Run integration tests (Selenium)
          command: |
            DC_NETWORK=$(docker network ls -f name=.*_default --format "{{.Name}}" | head -n 1)
            echo "Running tests on network: $DC_NETWORK"
            docker run \
              --rm \
              --network $DC_NETWORK \
              --shm-size="2g" \
              -e APP_URL="http://backend:5000/" \
              food-billing-selenium-tests:latest

      # --- Capture Backend Logs (Keep this!) ---
      - run:
          name: Capture Backend Logs
          command: docker-compose -f ~/project/docker-compose.yml logs backend
          when: always # Always run this step

      # Optional: Capture DB Logs on failure too
      - run:
          name: Capture DB Logs
          command: docker-compose -f ~/project/docker-compose.yml logs db
          when: always # Always run this step

      # Optional: Add steps here to store test results or artifacts if your tests generate them

  # ... push and deploy jobs ...
  push:
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker
      - run:
          name: Load Docker images
          command: |
            docker load -i ~/project/backend.tar
            docker tag swe40006_devops-backend:latest $ACR_NAME.azurecr.io/swe40006_devops-backend:latest

            docker load -i ~/project/frontend.tar
            docker tag swe40006_devops-frontend:latest $ACR_NAME.azurecr.io/swe40006_devops-frontend:latest
      - run:
          name: Push backend to ACR
          command: |
            echo $AZURE_PASSWORD | docker login $ACR_NAME.azurecr.io -u $AZURE_USERNAME --password-stdin
            docker push $ACR_NAME.azurecr.io/swe40006_devops-backend:latest
      - run:
          name: Push frontend to ACR
          command: |
            docker push $ACR_NAME.azurecr.io/swe40006_devops-frontend:latest

  deploy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Azure CLI and Kubectl
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

            KUBECTL_VERSION=$(curl -sL https://dl.k8s.io/release/stable.txt)
            echo "Installing kubectl version $KUBECTL_VERSION"
            curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/kubectl
      - run:
          name: Login to Azure and set AKS credentials
          command: |
            az login --service-principal -u $AZURE_SP_APP_ID -p $AZURE_SP_CLIENT_SECRET --tenant $AZURE_TENANT_ID
            az aks get-credentials --resource-group "$AZURE_RESOURCE_GROUP" --name "$AKS_CLUSTER_NAME" --overwrite-existing
      - run:
          name: Deploy backend and frontend to AKS
          command: |
            kubectl apply -f k8s/db-secret.yaml
            kubectl apply -f k8s/backend-deployment.yaml
            kubectl apply -f k8s/backend-service.yaml
            kubectl apply -f k8s/frontend-deployment.yaml
            kubectl apply -f k8s/frontend-service.yaml
      - run:
          name: Restart Deployments to Pick Up Changes
          command: |
            kubectl rollout restart deployment backend-deployment
            kubectl rollout restart deployment frontend-deployment


workflows:
  build_test_push:
    jobs:
      - build
      - test:
          requires:
            - build
      - push:
          requires:
            - test
      - deploy:
          requires:
            - push