version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t foodbilling:latest -f templates/Dockerfile .
            docker save foodbilling:latest > foodbilling_latest.tar
      - persist_to_workspace:
          root: ~/project
          paths:
            - foodbilling_latest.tar

  test:
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker
      - run:
          name: Load Docker image
          command: docker load -i ~/project/foodbilling_latest.tar
      - run:
          name: Run tests
          command: docker run --rm foodbilling:latest python program_test.py

          command: echo "Run your Selenium or integration tests here"
  push:
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker
      - run:
          name: Load Docker image
          command: docker load -i ~/project/foodbilling_latest.tar
      - run:
          name: Docker Login
          command: echo $AZURE_PASSWORD | docker login $ACR_NAME.azurecr.io -u $AZURE_USERNAME --password-stdin
      - run:
          name: Docker Push
          command: docker tag foodbilling:latest $ACR_NAME.azurecr.io/foodbilling:latest
      - run:
          name: Push Docker Image
          command: docker push $ACR_NAME.azurecr.io/foodbilling:latest

workflows:
  build_test_push:
    jobs:
      - build
      - test:
          requires:
            - build
      - push:
          requires:
            - test
