version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          command: docker build -t $ACR_NAME.azurecr.io/foodbilling:latest -f backend/Dockerfile .

  test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run Tests
          command: echo "Run your Selenium or unit tests here"

  push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login and Push
          command: |
            echo $AZURE_PASSWORD | docker login $ACR_NAME.azurecr.io -u $AZURE_USERNAME --password-stdin
            docker push $ACR_NAME.azurecr.io/foodbilling:latest

  deploy:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - run:
          name: Deploy Container from ACR
          command: |
            docker run -d \
              -p ${APP_HOST_PORT}:${APP_CONTAINER_PORT} \
              -e DB_HOST=${DB_HOST_FQDN} \
              -e DB_PORT=5432 \
              -e DB_NAME=${DB_NAME_SUGGESTION} \
              -e DB_USER=${DB_USER_FROM_TF_VAR} \
              -e DB_PASSWORD=${DB_PASSWORD_FROM_TF_VAR} \
              --restart always \
              --name myapp_container \
              ${ACR_IMAGE_FULL_PATH}

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - push:
          requires:
            - test
      - deploy:
          requires:
            - push
