apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  DB_HOST: myapp-pgflex.postgres.database.azure.com
  DB_NAME: postgres
  DB_USER: swe40006devops
  DB_PASSWORD: SWE40006devops
