apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: swe40006billingacr.azurecr.io/swe40006_devops-frontend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "db-service"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER
            - name: REACT_APP_API_URL
              value: "http://backend-service:5000"
